[package]
name    = "add"
version = "0.1.0"
authors = ["thomas.darimont@gmail.com"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "add.rs"

[profile.release]
opt-level = 0
lto = "off"
codegen-units = 1